"""
Unit tests for the ZLang C++ Code Generator.

Rather than compiling and executing the generated C++, these tests verify:
  * that the generated code contains expected C++ constructs (string matching)
  * that the full pipeline (lex → parse → analyze → codegen) succeeds
  * structural properties (includes, function signatures, etc.)
"""
import pytest
from src.lexer import Lexer
from src.parser import Parser
from src.semantic import SemanticAnalyzer
from src.codegen import CodeGenerator


def generate(source: str) -> str:
    """Run the full pipeline and return the generated C++ string."""
    tokens = Lexer(source).tokenize()
    ast = Parser(tokens).parse()
    SemanticAnalyzer().analyze(ast)
    return CodeGenerator().generate(ast)


# ── Header / preamble ─────────────────────────────────────────────────────

class TestHeader:
    def test_includes_iostream(self):
        cpp = generate("func main() -> void {}")
        assert "#include <iostream>" in cpp

    def test_includes_string(self):
        cpp = generate("func main() -> void {}")
        assert "#include <string>" in cpp

    def test_has_generator_comment(self):
        cpp = generate("func main() -> void {}")
        assert "Generated by ZLang compiler" in cpp


# ── main() mapping ────────────────────────────────────────────────────────

class TestMainFunction:
    def test_main_returns_int(self):
        cpp = generate("func main() -> void {}")
        assert "int main()" in cpp

    def test_main_has_return_zero(self):
        cpp = generate("func main() -> void {}")
        assert "return 0;" in cpp


# ── Type mapping ──────────────────────────────────────────────────────────

class TestTypeMapping:
    def test_int_param(self):
        cpp = generate("func f(n: int) -> int { return n }")
        assert "int f(int n)" in cpp

    def test_float_param(self):
        cpp = generate("func f(x: float) -> float { return x }")
        assert "double f(double x)" in cpp

    def test_bool_param(self):
        cpp = generate("func f(b: bool) -> bool { return b }")
        assert "bool f(bool b)" in cpp

    def test_string_param(self):
        cpp = generate('func f(s: string) -> string { return s }')
        assert "std::string f(std::string s)" in cpp

    def test_void_return(self):
        cpp = generate("func f() -> void {}")
        assert "void f()" in cpp


# ── Variable declarations ─────────────────────────────────────────────────

class TestVarDecl:
    def test_int_var(self):
        cpp = generate("func f() -> void { let x: int = 5 }")
        assert "int x = 5;" in cpp

    def test_float_var(self):
        cpp = generate("func f() -> void { let x: float = 3.14 }")
        assert "double x = 3.14" in cpp

    def test_bool_var_true(self):
        cpp = generate("func f() -> void { let b: bool = true }")
        assert "bool b = true;" in cpp

    def test_string_var(self):
        cpp = generate('func f() -> void { let s: string = "hello" }')
        assert 'std::string s = "hello";' in cpp

    def test_inferred_type_var(self):
        cpp = generate("func f() -> void { let x = 10 }")
        assert "int x = 10;" in cpp


# ── Assignment ────────────────────────────────────────────────────────────

class TestAssignment:
    def test_simple_assignment(self):
        cpp = generate("func f() -> void { let x: int = 0  x = 42 }")
        assert "x = 42;" in cpp


# ── Print statement ───────────────────────────────────────────────────────

class TestPrint:
    def test_print_int(self):
        cpp = generate("func f() -> void { print(1) }")
        assert "std::cout" in cpp
        assert "1" in cpp

    def test_print_string(self):
        cpp = generate('func f() -> void { print("hi") }')
        assert '"hi"' in cpp


# ── Control flow ──────────────────────────────────────────────────────────

class TestControlFlow:
    def test_if_statement(self):
        cpp = generate("func f() -> void { if true { print(1) } }")
        assert "if (true)" in cpp

    def test_if_else_statement(self):
        cpp = generate("func f() -> void { if true { print(1) } else { print(2) } }")
        assert "} else {" in cpp

    def test_while_loop(self):
        cpp = generate("func f() -> void { let x: int = 0  while x < 5 { x = x + 1 } }")
        assert "while (" in cpp
        assert "x < 5" in cpp

    def test_for_loop(self):
        cpp = generate("func f() -> void { for i in range(0, 10) { print(i) } }")
        assert "for (int i = 0; i < 10; ++i)" in cpp


# ── Operators ─────────────────────────────────────────────────────────────

class TestOperators:
    def test_addition(self):
        cpp = generate("func f() -> void { let r = 1 + 2 }")
        assert "(1 + 2)" in cpp

    def test_subtraction(self):
        cpp = generate("func f() -> void { let r = 5 - 3 }")
        assert "(5 - 3)" in cpp

    def test_multiplication(self):
        cpp = generate("func f() -> void { let r = 2 * 3 }")
        assert "(2 * 3)" in cpp

    def test_logical_and(self):
        cpp = generate("func f() -> void { let b = true and false }")
        assert "&&" in cpp

    def test_logical_or(self):
        cpp = generate("func f() -> void { let b = true or false }")
        assert "||" in cpp

    def test_not(self):
        cpp = generate("func f() -> void { let b = not true }")
        assert "!(true)" in cpp

    def test_unary_minus(self):
        cpp = generate("func f() -> void { let x = -5 }")
        assert "-(5)" in cpp

    def test_comparison_lte(self):
        cpp = generate("func f(x: int) -> bool { return x <= 10 }")
        assert "<=" in cpp


# ── Function calls ────────────────────────────────────────────────────────

class TestFuncCall:
    def test_call_no_args(self):
        cpp = generate("func g() -> void {} func f() -> void { g() }")
        assert "g()" in cpp

    def test_call_with_args(self):
        cpp = generate(
            "func add(a: int, b: int) -> int { return a + b } "
            "func f() -> void { let r = add(1, 2) }"
        )
        assert "add(1, 2)" in cpp


# ── Return statement ──────────────────────────────────────────────────────

class TestReturn:
    def test_return_value(self):
        cpp = generate("func id(x: int) -> int { return x }")
        assert "return x;" in cpp

    def test_return_void(self):
        cpp = generate("func f() -> void { return }")
        assert "return;" in cpp


# ── String escaping ───────────────────────────────────────────────────────

class TestStringEscaping:
    def test_newline_in_string(self):
        cpp = generate('func f() -> void { let s: string = "a\\nb" }')
        # The generated C++ should contain the escaped newline
        assert "\\n" in cpp


# ── Full example programs ─────────────────────────────────────────────────

class TestFullPrograms:
    def test_hello_world(self):
        src = 'func main() -> void { print("Hello, World!") }'
        cpp = generate(src)
        assert "Hello, World!" in cpp

    def test_fibonacci(self):
        src = """
func fibonacci(n: int) -> int {
    if n <= 1 {
        return n
    }
    return fibonacci(n - 1) + fibonacci(n - 2)
}
func main() -> void {
    print(fibonacci(10))
}
"""
        cpp = generate(src)
        assert "fibonacci" in cpp
        assert "return 0;" in cpp

    def test_factorial(self):
        src = """
func factorial(n: int) -> int {
    if n <= 1 { return 1 }
    return n * factorial(n - 1)
}
func main() -> void {
    for i in range(1, 6) { print(factorial(i)) }
}
"""
        cpp = generate(src)
        assert "factorial" in cpp
        assert "for (int i = 1; i < 6; ++i)" in cpp
