"""
C++ Code Generator for ZLang.

Traverses the type-annotated AST produced after semantic analysis and emits
valid C++17 source code.

Type mapping
────────────
  ZLang   →  C++
  int     →  int
  float   →  double
  bool    →  bool
  string  →  std::string
  void    →  void

Built-in constructs
───────────────────
  print(x)              →  std::cout << x << '\\n';
  for j in range(a, b)  →  for (int j = <a>; j < <b>; ++j)
"""
from typing import List
from .ast_nodes import (
    Program, FuncDecl, Block,
    VarDecl, Assignment, IfStmt, WhileStmt, ForStmt,
    ReturnStmt, PrintStmt, ExprStmt,
    BinOp, UnaryOp,
    IntLiteral, FloatLiteral, StringLiteral, BoolLiteral,
    Identifier, FuncCall,
)


# ---------------------------------------------------------------------------
# Error
# ---------------------------------------------------------------------------

class CodeGenError(Exception):
    def __init__(self, message: str, line: int = 0, col: int = 0) -> None:
        super().__init__(f"CodeGen error at line {line}, col {col}: {message}")


# ---------------------------------------------------------------------------
# Type mapping
# ---------------------------------------------------------------------------

_CPP_TYPES = {
    "int":    "int",
    "float":  "double",
    "bool":   "bool",
    "string": "std::string",
    "void":   "void",
}


def _cpp_type(zlang_type: str) -> str:
    return _CPP_TYPES.get(zlang_type, zlang_type)


# ---------------------------------------------------------------------------
# Code Generator
# ---------------------------------------------------------------------------

class CodeGenerator:
    """Emits a C++ translation unit from a ZLang AST."""

    def __init__(self, indent_size: int = 4) -> None:
        self._indent = 0
        self._indent_size = indent_size
        self._lines: List[str] = []

    # ── Helpers ──────────────────────────────────────────────────────────────

    def _emit(self, line: str = "") -> None:
        if line:
            self._lines.append(" " * self._indent + line)
        else:
            self._lines.append("")

    def _push(self) -> None:
        self._indent += self._indent_size

    def _pop(self) -> None:
        self._indent -= self._indent_size

    # ── Public entry point ────────────────────────────────────────────────

    def generate(self, program: Program) -> str:
        """Return the complete C++ source string for *program*."""
        self._lines = []
        self._emit_header()
        for func in program.functions:
            self._emit("")
            self._gen_func(func)
        return "\n".join(self._lines) + "\n"

    # ── Header / preamble ─────────────────────────────────────────────────

    def _emit_header(self) -> None:
        self._emit("// Generated by ZLang compiler")
        self._emit("#include <iostream>")
        self._emit("#include <string>")
        self._emit("")
        # Forward-declare all functions so order in source doesn't matter
        # (declarations will be emitted inline as part of full definitions)

    # ── Function ─────────────────────────────────────────────────────────

    def _gen_func(self, func: FuncDecl) -> None:
        params_str = ", ".join(
            f"{_cpp_type(p.type.name)} {p.name}" for p in func.params
        )
        ret = _cpp_type(func.return_type.name)
        # Use C-style main signature when the function is 'main'
        if func.name == "main":
            self._emit(f"int main() {{")
        else:
            self._emit(f"{ret} {func.name}({params_str}) {{")
        self._push()
        self._gen_block_body(func.body)
        # Add return 0 for main if not present
        if func.name == "main":
            self._emit("return 0;")
        self._pop()
        self._emit("}")

    # ── Block (without surrounding braces – caller emits them) ───────────

    def _gen_block_body(self, block: Block) -> None:
        for stmt in block.statements:
            self._gen_stmt(stmt)

    def _gen_block(self, block: Block) -> None:
        """Emit a block including its opening and closing braces."""
        self._emit("{")
        self._push()
        self._gen_block_body(block)
        self._pop()
        self._emit("}")

    # ── Statements ────────────────────────────────────────────────────────

    def _gen_stmt(self, stmt) -> None:
        if isinstance(stmt, VarDecl):
            self._gen_var_decl(stmt)
        elif isinstance(stmt, Assignment):
            self._gen_assignment(stmt)
        elif isinstance(stmt, IfStmt):
            self._gen_if(stmt)
        elif isinstance(stmt, WhileStmt):
            self._gen_while(stmt)
        elif isinstance(stmt, ForStmt):
            self._gen_for(stmt)
        elif isinstance(stmt, ReturnStmt):
            self._gen_return(stmt)
        elif isinstance(stmt, PrintStmt):
            self._gen_print(stmt)
        elif isinstance(stmt, ExprStmt):
            self._emit(f"{self._gen_expr(stmt.expr)};")
        else:
            raise CodeGenError(f"Unknown statement type: {type(stmt).__name__}")

    def _gen_var_decl(self, stmt: VarDecl) -> None:
        # resolved_type is set by semantic analysis
        resolved = getattr(stmt.value, "resolved_type", None)
        if stmt.type_annotation is not None:
            ctype = _cpp_type(stmt.type_annotation.name)
        elif resolved:
            ctype = _cpp_type(resolved)
        else:
            ctype = "auto"
        self._emit(f"{ctype} {stmt.name} = {self._gen_expr(stmt.value)};")

    def _gen_assignment(self, stmt: Assignment) -> None:
        self._emit(f"{stmt.name} = {self._gen_expr(stmt.value)};")

    def _gen_if(self, stmt: IfStmt) -> None:
        self._emit(f"if ({self._gen_expr(stmt.condition)}) {{")
        self._push()
        self._gen_block_body(stmt.then_block)
        self._pop()
        if stmt.else_block is not None:
            self._emit("} else {")
            self._push()
            self._gen_block_body(stmt.else_block)
            self._pop()
        self._emit("}")

    def _gen_while(self, stmt: WhileStmt) -> None:
        self._emit(f"while ({self._gen_expr(stmt.condition)}) {{")
        self._push()
        self._gen_block_body(stmt.body)
        self._pop()
        self._emit("}")

    def _gen_for(self, stmt: ForStmt) -> None:
        start = self._gen_expr(stmt.start)
        end = self._gen_expr(stmt.end)
        self._emit(f"for (int {stmt.var} = {start}; {stmt.var} < {end}; ++{stmt.var}) {{")
        self._push()
        self._gen_block_body(stmt.body)
        self._pop()
        self._emit("}")

    def _gen_return(self, stmt: ReturnStmt) -> None:
        if stmt.value is None:
            self._emit("return;")
        else:
            self._emit(f"return {self._gen_expr(stmt.value)};")

    def _gen_print(self, stmt: PrintStmt) -> None:
        self._emit(f"std::cout << {self._gen_expr(stmt.value)} << '\\n';")

    # ── Expressions ───────────────────────────────────────────────────────

    def _gen_expr(self, node) -> str:
        if isinstance(node, IntLiteral):
            return str(node.value)

        if isinstance(node, FloatLiteral):
            # Ensure the literal has a decimal point so C++ treats it as double
            s = repr(node.value)
            if "." not in s and "e" not in s.lower():
                s += ".0"
            return s

        if isinstance(node, BoolLiteral):
            return "true" if node.value else "false"

        if isinstance(node, StringLiteral):
            # Escape special characters
            escaped = (
                node.value
                .replace("\\", "\\\\")
                .replace('"', '\\"')
                .replace("\n", "\\n")
                .replace("\t", "\\t")
            )
            return f'"{escaped}"'

        if isinstance(node, Identifier):
            return node.name

        if isinstance(node, FuncCall):
            args = ", ".join(self._gen_expr(a) for a in node.args)
            return f"{node.name}({args})"

        if isinstance(node, UnaryOp):
            operand = self._gen_expr(node.operand)
            if node.op == "not":
                return f"!({operand})"
            if node.op == "-":
                return f"-({operand})"
            raise CodeGenError(f"Unknown unary op: {node.op!r}")

        if isinstance(node, BinOp):
            return self._gen_binop(node)

        raise CodeGenError(f"Unknown expression type: {type(node).__name__}")

    def _gen_binop(self, node: BinOp) -> str:
        left = self._gen_expr(node.left)
        right = self._gen_expr(node.right)
        op = node.op

        # Map ZLang operators to C++ operators
        op_map = {
            "and": "&&",
            "or":  "||",
            "not": "!",
            "==":  "==",
            "!=":  "!=",
            "<":   "<",
            ">":   ">",
            "<=":  "<=",
            ">=":  ">=",
            "+":   "+",
            "-":   "-",
            "*":   "*",
            "/":   "/",
            "%":   "%",
        }
        cpp_op = op_map.get(op)
        if cpp_op is None:
            raise CodeGenError(f"Unknown binary operator: {op!r}")
        return f"({left} {cpp_op} {right})"
